---
- name: add kubernetes repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    file: kubernetes_repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    enabled: yes

- name: deactivate selinux
  selinux:
    state: disabled
  changed_when: false # bug

- name: install kubernetes packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ kubebase_packages_centos }}'
