---
- name: include kubemaster ip
  include: ip.yml

- name: load centos part
  include: centos.yml
  when: ansible_os_family == "RedHat"

- name: load ubuntu part
  include: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: activate and enable services
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - docker
    - kubelet
